apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Package
metadata:
  name: faeb-system-enzymes
  namespace: eksa-system
spec:
  packageName: faeb-system-enzymes
  targetNamespace: faeb-system
  config: |
    # Faeb System Enzymes - Specialized Applications
    # These are the enzymes that perform specific transformations
    # on our catalytic EKS Anywhere infrastructure
    
    enzymes:
      # Audio Processing Enzyme
      haskell-daw:
        image: "faeb-system/haskell-daw:latest"
        replicas: 2
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
      # Visual Processing Enzyme  
      parametric-visualizer:
        image: "faeb-system/parametric-visualizer:latest"
        replicas: 1
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
            
      # AI Analysis Enzyme
      future-wave-analyzer:
        image: "faeb-system/future-wave-analyzer:latest"
        replicas: 3
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
            
      # Nix Package Manager Enzyme
      nix-catalyst:
        image: "faeb-system/nix-catalyst:latest"
        replicas: 1
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
            
    # Enzyme Coordination
    coordination:
      serviceMesh: "istio"
      monitoring: "prometheus-grafana"
      logging: "loki-promtail"
      
    # Three Breaths Integration
    threeBreaths:
      firstBreath: "haskell-creation"
      secondBreath: "nix-reproducibility"  
      thirdBreath: "faeb-visualization"
